# Travis file

language: generic

before_install:
  - if [${TRAVIS_OS_NAME} == "linux"]; then sudo apt-get update -qq; fi
  - test/install-dependencies.sh

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'libblas-dev', 'liblapack-dev', 'libopenblas-dev', 'libtiff5-dev']
      env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXXOMP -DCMAKE_C_COMPILER=$CCOMP -DBUILD_EXECUTABLE=ON ..
  - make
  - sudo make install

notifications:
  email: false
